# Generated by Django 6.0.2 on 2026-02-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_contact_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='photo',
            new_name='profile_image',
        ),
    ]
